config/routes.rb
Rails.application.routes.draw do
  resources :torrents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/torrent.rb
class Torrent < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/torrents_controller.rb
class TorrentsController < ApplicationController
  before_action :set_torrent, only: %i[ show edit update destroy ]

  # GET /torrents or /torrents.json
  def index
    @torrents = Torrent.all
  end

  # GET /torrents/1 or /torrents/1.json
  def show
  end

  # GET /torrents/new
  def new
    @torrent = Torrent.new
  end

  # GET /torrents/1/edit
  def edit
  end

  # POST /torrents or /torrents.json
  def create
    @torrent = Torrent.new(torrent_params)

    respond_to do |format|
      if @torrent.save
        format.html { redirect_to @torrent, notice: "Torrent was successfully created." }
        format.json { render :show, status: :created, location: @torrent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @torrent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /torrents/1 or /torrents/1.json
  def update
    respond_to do |format|
      if @torrent.update(torrent_params)
        format.html { redirect_to @torrent, notice: "Torrent was successfully updated." }
        format.json { render :show, status: :ok, location: @torrent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @torrent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /torrents/1 or /torrents/1.json
  def destroy
    @torrent.destroy
    respond_to do |format|
      format.html { redirect_to torrents_url, notice: "Torrent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_torrent
      @torrent = Torrent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def torrent_params
      params.require(:torrent).permit(:title, :release_year, :url, :main)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/torrents_helper.rb
module TorrentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Torscrap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/torrents/_form.html.erb
<%= form_with(model: torrent, local: true) do |form| %>
  <% if torrent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(torrent.errors.count, "error") %> prohibited this torrent from being saved:</h2>

      <ul>
        <% torrent.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :release_year %>
    <%= form.text_field :release_year %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :main %>
    <%= form.text_field :main %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/torrents/edit.html.erb
<h1>Editing Torrent</h1>

<%= render 'form', torrent: @torrent %>

<%= link_to 'Show', @torrent %> |
<%= link_to 'Back', torrents_path %>

app/views/torrents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Torrents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Release year</th>
      <th>Url</th>
      <th>Main</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @torrents.each do |torrent| %>
      <tr>
        <td><%= torrent.title %></td>
        <td><%= torrent.release_year %></td>
        <td><%= torrent.url %></td>
        <td><%= torrent.main %></td>
        <td><%= link_to 'Show', torrent %></td>
        <td><%= link_to 'Edit', edit_torrent_path(torrent) %></td>
        <td><%= link_to 'Destroy', torrent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Torrent', new_torrent_path %>

app/views/torrents/new.html.erb
<h1>New Torrent</h1>

<%= render 'form', torrent: @torrent %>

<%= link_to 'Back', torrents_path %>

app/views/torrents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @torrent.title %>
</p>

<p>
  <strong>Release year:</strong>
  <%= @torrent.release_year %>
</p>

<p>
  <strong>Url:</strong>
  <%= @torrent.url %>
</p>

<p>
  <strong>Main:</strong>
  <%= @torrent.main %>
</p>

<%= link_to 'Edit', edit_torrent_path(@torrent) %> |
<%= link_to 'Back', torrents_path %>